### ISSUE TITLE
Boot loop ESP32-WROOM-32

### ISSUE THREAD

**Issue by dennisdebel** [tobozo/ESP32-BLEBeaconSpam#2]
According to the serial monitor, the ESP32 seems to be crashing after generating one packet. Serial output below.

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5856
entry 0x400806a8
Random mac prefix: 1F32
New Mac: 0:1F:32:F2:AC:76
Random vendor prefix: 638 = 6:38 to littleEndian => 3806
Random UUID : b1f21d4c-6b2a-8ef6-5d32-abe50f38a6ce
ets Jun  8 2016 00:22:57

I tried different memory speeds etc and board settings, to no avail.

**Comment by tobozo** [comment]
a boot loop is what you should expect from this sketch, so unless you have a guru meditation or any significant error message, this behaviour is totally normal

![image](https://user-images.githubusercontent.com/1893754/201231449-9e847302-6143-4256-8fc1-fddc6dcf7aa3.png)

**Comment by dennisdebel** [comment]
I see! Thank you for clearing it up!
